const $=s=>document.querySelector(s);
const KEY='tilki-core-multilingual-v4';
const APPS={github:'https://github.com/tilkitaha',gmail:'https://mail.google.com/',calendar:'https://calendar.google.com/',linkedin:'https://www.linkedin.com/',chatgpt:'https://chatgpt.com/',youtube:'https://www.youtube.com/',spotify:'https://open.spotify.com/'};
const LANG={
 tr:{speech:'tr-TR',ready:'HAZIR',listen:'DİNLİYOR',think:'İŞLİYOR',done:'TAMAMLANDI',open:'AÇIK GÖREV',completed:'TAMAMLANDI',memory:'HAFIZADA',noTasks:'Henüz görev yok',noMemory:'Hafıza boş',today:'Bugünkü odağın:',notFound:'Bu görevi bulamadım.',goalReady:'Hedefini 5 adıma dönüştürdüm.',queueReady:'Görev kuyruğu hazır.',saved:'Hafızaya kaydettim:',taskMade:'Görev oluşturuldu:',welcome:'Memnun oldum',remember:'Seni bu cihazda hatırlayacağım.',emptyTasks:'Açık görevin yok.',emptyMemory:'Hafızam boş.',openApp:'açılıyor.',fallback:'Bir hedef vererek başla. Örnek: “Hedefim veri analisti olmak”.',help:'Hedef planlayabilir, görev oluşturabilir, söylediklerini hatırlayabilir, günlük odak planı verebilir ve uygulamaları açabilirim.'},
 en:{speech:'en-US',ready:'READY',listen:'LISTENING',think:'PROCESSING',done:'DONE',open:'OPEN TASK',completed:'COMPLETED',memory:'IN MEMORY',noTasks:'No tasks yet',noMemory:'Memory is empty',today:'Your focus today:',notFound:'I could not find that task.',goalReady:'I turned your goal into 5 steps.',queueReady:'Mission queue is ready.',saved:'Saved to memory:',taskMade:'Task created:',welcome:'Nice to meet you',remember:'I will remember you on this device.',emptyTasks:'You have no open tasks.',emptyMemory:'My memory is empty.',openApp:'is opening.',fallback:'Start by giving me a goal. Example: “My goal is to become a data analyst”.',help:'I can plan goals, create tasks, remember information, build a daily focus plan, and open supported apps.'},
 pl:{speech:'pl-PL',ready:'GOTOWY',listen:'SŁUCHAM',think:'PRZETWARZAM',done:'GOTOWE',open:'OTWARTE ZADANIE',completed:'UKOŃCZONE',memory:'W PAMIĘCI',noTasks:'Brak zadań',noMemory:'Pamięć jest pusta',today:'Twój plan na dziś:',notFound:'Nie znalazłem tego zadania.',goalReady:'Podzieliłem Twój cel na 5 kroków.',queueReady:'Lista zadań jest gotowa.',saved:'Zapisałem w pamięci:',taskMade:'Utworzono zadanie:',welcome:'Miło Cię poznać',remember:'Zapamiętam Cię na tym urządzeniu.',emptyTasks:'Nie masz otwartych zadań.',emptyMemory:'Moja pamięć jest pusta.',openApp:'otwieram.',fallback:'Zacznij od podania celu. Przykład: „Moim celem jest zostać analitykiem danych”.',help:'Mogę planować cele, tworzyć zadania, zapamiętywać informacje, przygotować plan dnia i otwierać aplikacje.'},
 de:{speech:'de-DE',ready:'BEREIT',listen:'HÖRE ZU',think:'VERARBEITUNG',done:'ERLEDIGT',open:'OFFENE AUFGABE',completed:'ERLEDIGT',memory:'GESPEICHERT',noTasks:'Noch keine Aufgaben',noMemory:'Speicher ist leer',today:'Dein Fokus heute:',notFound:'Ich konnte diese Aufgabe nicht finden.',goalReady:'Ich habe dein Ziel in 5 Schritte aufgeteilt.',queueReady:'Die Aufgabenliste ist bereit.',saved:'Gespeichert:',taskMade:'Aufgabe erstellt:',welcome:'Freut mich',remember:'Ich merke mir dich auf diesem Gerät.',emptyTasks:'Du hast keine offenen Aufgaben.',emptyMemory:'Mein Speicher ist leer.',openApp:'wird geöffnet.',fallback:'Gib mir zuerst ein Ziel. Beispiel: „Mein Ziel ist Data Analyst zu werden”.',help:'Ich kann Ziele planen, Aufgaben erstellen, Informationen merken, deinen Tag planen und Apps öffnen.'},
 es:{speech:'es-ES',ready:'LISTO',listen:'ESCUCHANDO',think:'PROCESANDO',done:'HECHO',open:'TAREA ABIERTA',completed:'COMPLETADA',memory:'EN MEMORIA',noTasks:'Aún no hay tareas',noMemory:'La memoria está vacía',today:'Tu enfoque de hoy:',notFound:'No encontré esa tarea.',goalReady:'Convertí tu objetivo en 5 pasos.',queueReady:'La cola de tareas está lista.',saved:'Guardado en memoria:',taskMade:'Tarea creada:',welcome:'Encantado de conocerte',remember:'Te recordaré en este dispositivo.',emptyTasks:'No tienes tareas abiertas.',emptyMemory:'Mi memoria está vacía.',openApp:'se está abriendo.',fallback:'Empieza dándome un objetivo. Ejemplo: “Mi objetivo es ser analista de datos”.',help:'Puedo planificar objetivos, crear tareas, recordar información, organizar tu día y abrir aplicaciones.'},
 fr:{speech:'fr-FR',ready:'PRÊT',listen:'J’ÉCOUTE',think:'TRAITEMENT',done:'TERMINÉ',open:'TÂCHE OUVERTE',completed:'TERMINÉE',memory:'EN MÉMOIRE',noTasks:'Aucune tâche',noMemory:'La mémoire est vide',today:'Ton focus aujourd’hui :',notFound:'Je n’ai pas trouvé cette tâche.',goalReady:'J’ai transformé ton objectif en 5 étapes.',queueReady:'La file de tâches est prête.',saved:'Enregistré en mémoire :',taskMade:'Tâche créée :',welcome:'Ravi de te rencontrer',remember:'Je me souviendrai de toi sur cet appareil.',emptyTasks:'Tu n’as aucune tâche ouverte.',emptyMemory:'Ma mémoire est vide.',openApp:'s’ouvre.',fallback:'Commence par me donner un objectif. Exemple : « Mon objectif est de devenir data analyst ».',help:'Je peux planifier des objectifs, créer des tâches, mémoriser des informations, organiser ta journée et ouvrir des applications.'}
};
function browserLang(){const l=(navigator.language||'en').toLowerCase();if(l.startsWith('tr'))return'tr';if(l.startsWith('pl'))return'pl';if(l.startsWith('de'))return'de';if(l.startsWith('es'))return'es';if(l.startsWith('fr'))return'fr';return'en'}
function detectLang(s){const q=' '+s.toLowerCase()+' ';const scores={tr:0,en:0,pl:0,de:0,es:0,fr:0};const tests={tr:[/[çğıöşü]/,/\b(hedefim|görev|hatırla|bugün|aç|benim adım|yardım|istiyorum)\b/g],pl:[/[ąćęłńóśźż]/,/\b(cel|zadanie|zapamiętaj|dzisiaj|dziś|otwórz|nazywam|chcę|pomoc)\b/g],de:[/[äöüß]/,/\b(ziel|aufgabe|merke|heute|öffne|heiße|möchte|hilfe)\b/g],es:[/[áéíóúñ¿¡]/,/\b(objetivo|tarea|recuerda|hoy|abre|llamo|quiero|ayuda)\b/g],fr:[/[àâçéèêëîïôùûüÿœ]/,/\b(objectif|tâche|souviens|aujourd'hui|ouvre|appelle|veux|aide)\b/g],en:[/\b(the|my|goal|task|remember|today|open|name|want|help|should)\b/g]};for(const [k,arr] of Object.entries(tests))for(const r of arr){const m=q.match(r);if(m)scores[k]+=m.length*2}const best=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0];return best[1]>0?best[0]:(state.lang||browserLang())}
function base(){return{tasks:[],notes:[],activity:[],name:'',seen:false,lang:browserLang()}}
let state=(()=>{try{return{...base(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return base()}})();let recognition=null;
function id(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function log(text,type='SYSTEM'){state.activity.unshift({id:id(),text,type});state.activity=state.activity.slice(0,30)}
function esc(s=''){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function L(){return LANG[state.lang]||LANG.en}
function render(){const l=L(),o=state.tasks.filter(t=>!t.done),d=state.tasks.filter(t=>t.done),n=state.tasks.length,p=n?Math.round(d.length/n*100):0;$('#open').textContent=o.length;$('#done').textContent=d.length;$('#notesN').textContent=state.notes.length;$('#pct').textContent=p+'%';$('#progressBar').style.width=p+'%';$('#identity').textContent=(state.name?state.name.toLocaleUpperCase():state.lang.toUpperCase()+' // AUTO');$('#tasks').innerHTML=state.tasks.slice(0,12).map(t=>`<div class="item ${t.done?'done':''}"><button class="check" data-task="${t.id}">${t.done?'✓':''}</button><div class="txt">${esc(t.title)}<small>${t.done?l.completed:l.open}</small></div></div>`).join('')||`<div class="item"><div class="txt">${l.noTasks}</div></div>`;$('#notes').innerHTML=state.notes.slice(0,8).map(n=>`<div class="item"><div class="txt">${esc(n.text)}<small>${l.memory}</small></div></div>`).join('')||`<div class="item"><div class="txt">${l.noMemory}</div></div>`;$('#mode').textContent=l.ready}
function coreMode(m=''){const l=L(),c=$('#core');c.className='core'+(m?' '+m:'');$('#mode').textContent=m==='listen'?l.listen:m==='think'?l.think:m==='done'?l.done:l.ready;if(m==='done')setTimeout(()=>coreMode(''),900)}
function bubble(role,text){const d=document.createElement('div');d.className='msg '+(role==='me'?'me':'ai');d.textContent=text;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight}
function speak(text,lang=state.lang){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/\n/g,'. '));u.lang=(LANG[lang]||LANG.en).speech;u.rate=.98;const v=speechSynthesis.getVoices().find(x=>x.lang.toLowerCase().startsWith(u.lang.slice(0,2).toLowerCase()));if(v)u.voice=v;speechSynthesis.speak(u)}
function clean(s){return s.replace(/^\s*(?:tilki|tilki core|jarvis)[,\s:-]*/i,'').trim()}
function addTask(title){const t={id:id(),title:title.trim(),done:false,lang:state.lang};state.tasks.unshift(t);log(title,'TASK');return t}
function addNote(text){const n={id:id(),text:text.trim(),lang:state.lang};state.notes.unshift(n);log(text,'MEMORY');return n}
