function genericPlan(goal){const q=goal.toLowerCase();const set=PLANS[state.lang]||PLANS.en;if(/python|code|coding|program|kod|programlama|programmieren|programación|programmation/.test(q))return set.code;if(/job|career|cv|analyst|iş|kariyer|veri|praca|kariera|analityk|arbeit|karriere|analyst|empleo|carrera|analista|emploi|carrière|analyste/.test(q))return set.career;if(/thesis|tez|gridmind|praca dyplomowa|arbeit|tesis|mémoire|thèse/.test(q))return set.thesis;const g=goal;return state.lang==='tr'?[`“${g}” hedefini ölçülebilir hale getir`,'İlk küçük adımı belirle','Gerekli kaynakları listele','Bir kontrol noktası oluştur','Sonucu değerlendir ve devam et']:state.lang==='pl'?[`Zamień cel „${g}” na mierzalny wynik`,'Określ pierwszy mały krok','Wypisz potrzebne zasoby','Ustal punkt kontrolny','Oceń wynik i wybierz kolejny krok']:state.lang==='de'?[`Mache „${g}” messbar`,'Bestimme den ersten kleinen Schritt','Liste benötigte Ressourcen auf','Setze einen Kontrollpunkt','Bewerte das Ergebnis und mache weiter']:state.lang==='es'?[`Convierte “${g}” en un resultado medible`,'Define el primer paso pequeño','Enumera los recursos necesarios','Crea un punto de control','Evalúa el resultado y continúa']:state.lang==='fr'?[`Transforme « ${g} » en résultat mesurable`,'Définis la première petite étape','Liste les ressources nécessaires','Crée un point de contrôle','Évalue le résultat et continue']:[`Turn “${g}” into a measurable outcome`,'Define the first small step','List the resources you need','Create a checkpoint','Evaluate the result and continue']}
function plan(goal){const s=genericPlan(goal),l=L();s.slice().reverse().forEach(addTask);addNote((state.lang==='tr'?'Aktif hedef: ':state.lang==='pl'?'Aktywny cel: ':state.lang==='de'?'Aktives Ziel: ':state.lang==='es'?'Objetivo activo: ':state.lang==='fr'?'Objectif actif : ':'Active goal: ')+goal);save();return `${l.goalReady}\n${s.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n${l.queueReady}`}
function openGoal(){$('#missionModal').classList.add('show');setTimeout(()=>$('#goalInput').focus(),50)}function closeGoal(){$('#missionModal').classList.remove('show')}
function extract(patterns,raw){for(const r of patterns){const m=raw.match(r);if(m)return m[1].trim()}return null}
function answer(input){const raw=clean(input.trim());state.lang=detectLang(raw);if(recognition)recognition.lang=L().speech;const q=raw.toLowerCase(),l=L();let x;
x=extract([/^(?:hedefim|amacım)[:\s]+(.+)$/i,/^(.+?)\s+istiyorum$/i,/^(?:my goal is|my goal:)\s*(.+)$/i,/^i want to\s+(.+)$/i,/^(?:moim celem jest|mój cel to)\s+(.+)$/i,/^chcę\s+(.+)$/i,/^(?:mein ziel ist|mein ziel:)\s*(.+)$/i,/^ich möchte\s+(.+)$/i,/^(?:mi objetivo es|mi objetivo:)\s*(.+)$/i,/^quiero\s+(.+)$/i,/^(?:mon objectif est|mon objectif :)\s*(.+)$/i,/^je veux\s+(.+)$/i],raw);if(x)return plan(x);
if(/^(hedefimi planla|plan my goal|zaplanuj mój cel|plane mein ziel|planifica mi objetivo|planifie mon objectif)$/i.test(raw)){openGoal();return null}
x=extract([/^(?:görev oluştur|görev ekle)[:\s]+(.+)$/i,/^(?:create task|add task)[:\s]+(.+)$/i,/^(?:dodaj zadanie|utwórz zadanie)[:\s]+(.+)$/i,/^(?:aufgabe erstellen|aufgabe hinzufügen)[:\s]+(.+)$/i,/^(?:crear tarea|agregar tarea|añadir tarea)[:\s]+(.+)$/i,/^(?:créer une tâche|ajouter une tâche)[:\s]+(.+)$/i],raw);if(x){const t=addTask(x);save();return l.taskMade+' '+t.title}
x=extract([/^(?:bunu hatırla|hatırla|not al)[:\s]+(.+)$/i,/^(?:remember|remember this|note)[:\s]+(.+)$/i,/^(?:zapamiętaj|zapisz)[:\s]+(.+)$/i,/^(?:merke dir|merken)[:\s]+(.+)$/i,/^(?:recuerda|recuerda esto)[:\s]+(.+)$/i,/^(?:souviens-toi|mémorise|rappelle-toi)[:\s]+(.+)$/i],raw);if(x){const n=addNote(x);save();return l.saved+' '+n.text}
x=extract([/^(?:benim adım|adım)\s+(.+)$/i,/^my name is\s+(.+)$/i,/^(?:mam na imię|nazywam się)\s+(.+)$/i,/^(?:ich heiße|mein name ist)\s+(.+)$/i,/^(?:me llamo|mi nombre es)\s+(.+)$/i,/^(?:je m'appelle|mon nom est)\s+(.+)$/i],raw);if(x){state.name=x;addNote(x);save();return `${l.welcome} ${x}. ${l.remember}`}
if(/görevlerim|görevlerimi göster|show my tasks|list tasks|pokaż.*zadani|moje zadania|meine aufgaben|aufgaben anzeigen|mis tareas|mostrar.*tareas|mes tâches|affiche.*tâches/i.test(raw)){const o=state.tasks.filter(t=>!t.done);return o.length?o.map((t,i)=>`${i+1}. ${t.title}`).join('\n'):l.emptyTasks}
if(/hafızanda ne var|ne hatırlıyorsun|memory|what do you remember|co pamiętasz|pamięć|was weißt du|erinnerung|qué recuerdas|memoria|que mémorises|mémoire/i.test(raw))return state.notes.length?state.notes.map((n,i)=>`${i+1}. ${n.text}`).join('\n'):l.emptyMemory;
if(/bugün ne yapmalıyım|günümü planla|what should i do today|plan my day|co mam dziś zrobić|zaplanuj mój dzień|was soll ich heute tun|plane meinen tag|qué debo hacer hoy|planifica mi día|que dois-je faire aujourd'hui|planifie ma journée/i.test(raw)){const o=state.tasks.filter(t=>!t.done);return o.length?l.today+'\n'+o.slice(0,3).map((t,i)=>`${i+1}. ${t.title}`).join('\n'):l.emptyTasks}
if(/yardım|ne yapabilirsin|help|what can you do|pomoc|co potrafisz|hilfe|was kannst du|ayuda|qué puedes hacer|aide|que peux-tu faire/i.test(q))return l.help;
const appAliases={linkedin:'linkedin',github:'github',gmail:'gmail',calendar:'calendar',takvim:'calendar',kalendarz:'calendar',kalender:'calendar',calendario:'calendar',calendrier:'calendar',chatgpt:'chatgpt',youtube:'youtube',spotify:'spotify'};for(const [word,app] of Object.entries(appAliases)){if(q.includes(word)&&/(aç|open|otwórz|öffne|abre|ouvre)/i.test(q)){window.open(APPS[app],'_blank','noopener');log(app,'APP');save();return app+' '+l.openApp}}
return l.fallback}
